spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: TOKEN-SERVICE

# server:
#   port: 8085
#
# spring:
#   boot:
#     message: Hello, Token Service
#   application:
#     name: TOKEN-SERVICE
#   config:
#     import: optional:configserver:http://localhost:8888
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
#   datasource:
#     url: jdbc:mysql://localhost:3306/department_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=Africa/Luanda
#     username: root
#     password: hidden
#
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#
# eureka:
#   instance:
#     client:
#       serverUrl:
#         defaultZone: http://localhost:8761/eureka/
#
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health
#   tracing:
#     sampling:
#       probability: 1.0
#   endpoint:
#     health:
#       show-details: always
#
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
#   pattern:
#      level: '%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]'
