package com.wasp.avt.departmentservice.model.dto;


import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.validation.constraints.NotEmpty;

import java.time.LocalDateTime;

@Schema(
        description = "Department DTO model Information"
)
public record DepartmentDto(
        @Schema(
                description = "The ID for Department is required only for Method such as PUT and DELETE",
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        Long id,
        @Schema(
                description = "The value of this field is automatically generated by the API. (Optional)",
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        LocalDateTime createdAt,
        @Schema(
                description = "The value of this field is automatically generated by the API. (Optional)",
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        LocalDateTime lastModifiedAt,
        @Schema(
                description = "The value of this field is automatically generated by the API. (Optional)",
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        int totalModified,
        @Schema(
                description = "The name for Department is required",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @Column(nullable = false)
        @NotEmpty(message = "The field 'name' cannot be empty")
        String name,
        @Schema(
                description = "The description for Department is optional",
                requiredMode = Schema.RequiredMode.NOT_REQUIRED
        )
        String description,
        @Schema(
                description = "The code for Department is required",
                requiredMode = Schema.RequiredMode.REQUIRED
        )
        @Column(unique = true, nullable = false)
        @NotEmpty(message = "The field 'code' cannot be empty")
        String code) {


}
