spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: DEPARTMENT-SERVICE

# server:
#   port: 8080
# spring:
#   boot:
#     message: Hello, Department Service
#   application:
#     name: DEPARTMENT-SERVICE
#   config:
#     import: optional:configserver:http://localhost:8888
#   rabbitmq:
#     host: localhost
#     port: 5672
#     username: guest
#     password: guest
#
#   datasource:
#     url: jdbc:mysql://localhost:3306/department_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=Africa/Luanda
#     username: root
#     password: hidden
#
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#
# eureka:
#   instance:
#     client:
#       serverUrl:
#         defaultZone: http://localhost:8761/eureka/
#
# management:
#   endpoints:
#     web:
#       exposure:
#         include: health
#   tracing:
#     sampling:
#       probability: 1.0
#
#   # Actuator endpoints for Circuit Breaker
#   health:
#     circuitbreakers:
#       enabled: true
#   endpoint:
#     health:
#       show-details: always
#
# # Circuit Breaker Configuration
# resilience4j:
#   circuitbreaker:
#     instances:
#       DEPARTMENT-SERVICE:
#         registerHealthIndicator: true
#         failureRateThreshold: 50
#         minimumNumberOfCalls: 5
#         automaticTransitionFromOpenToHalfOpenEnabled: true
#         permittedNumberOfCallsInHalfOpenState: 3
#         waitDurationInOpenState: 5s
#         slidingWindowSize: 10
#         slidingWindowType: COUNT_BASED
#
# #Retry configuration
#   retry:
#     instances:
#       DEPARTMENT-SERVICE:
#         registerHealthIndicator: true
#         maxRetryAttempts: 5
#         waitDuration: 1s
#
# logging:
#   level:
#     org:
#       springframework:
#         web: DEBUG
#   pattern:
#      level: '%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]'
