server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/marianoj8/config-server-repo
          clone-on-start: true
          default-label: main
          username: marianoj8
          password: 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

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    health:
      show-details: always
